<script lang="ts">
	import { tooltip } from '$lib/actions/tooltip.svelte';
	import Confirm from '$lib/components/Confirm.svelte';
	import Layout from '$lib/components/Layout.svelte';
	import Table from '$lib/components/Table.svelte';
	import { PAGE_TRANSITION_DURATION } from '$lib/constants';
	import { AdminService } from '$lib/services/index.js';
	import { MessagesSquare, Trash2 } from 'lucide-svelte';
	import { fade } from 'svelte/transition';

	let { data } = $props();
	const { threads: initialThreads, users, projects } = data;
	let threads = $state(initialThreads);
	let loading = $state(false);

	let threadTableData = $derived(
		threads
			.filter((thread) => !thread.deleted && thread.assistantID && thread.projectID)
			.map((thread) => ({
				...thread,
				user: users.find((user) => user.id === thread.userID)?.email ?? 'Unknown',
				project: projects.find((project) => project.id === thread.projectID)?.name ?? 'Unknown'
			}))
	);
	let deletingThread = $state<(typeof threadTableData)[0]>();

	const duration = PAGE_TRANSITION_DURATION;
</script>

<Layout>
	<div class="my-4" in:fade={{ duration }} out:fade={{ duration }}>
		<div class="flex flex-col gap-8">
			<h1 class="text-2xl font-semibold">Chat Threads</h1>
			{#if threadTableData.length === 0}
				<div class="mt-12 flex w-md flex-col items-center gap-4 self-center text-center">
					<MessagesSquare class="size-24 text-gray-200 dark:text-gray-900" />
					<h4 class="text-lg font-semibold text-gray-400 dark:text-gray-600">No created threads</h4>
					<p class="text-sm font-light text-gray-400 dark:text-gray-600">
						Threads are generated by the user when they begin a Chat.
					</p>
				</div>
			{:else}
				<Table data={threadTableData} fields={['id', 'name', 'project', 'user', 'created']}>
					{#snippet actions(d)}
						<button
							class="icon-button hover:text-red-500"
							onclick={(e) => {
								e.stopPropagation();
								deletingThread = d;
							}}
							use:tooltip={'Delete Thread'}
						>
							<Trash2 class="size-4" />
						</button>
					{/snippet}
				</Table>
			{/if}
		</div>
	</div>
</Layout>

<Confirm
	msg={`Are you sure you want to delete this project?`}
	show={Boolean(deletingThread)}
	onsuccess={async () => {
		if (!deletingThread) return;
		loading = true;
		// await AdminService.deleteProject(deletingProject.assistantID, deletingProject.id);
		threads = await AdminService.listThreads();
		loading = false;
		deletingThread = undefined;
	}}
	oncancel={() => (deletingThread = undefined)}
	{loading}
/>

<svelte:head>
	<title>Obot | Chat Threads</title>
</svelte:head>
