<script lang="ts">
	import { tooltip } from '$lib/actions/tooltip.svelte';
	import Confirm from '$lib/components/Confirm.svelte';
	import Layout from '$lib/components/Layout.svelte';
	import Table from '$lib/components/Table.svelte';
	import { PAGE_TRANSITION_DURATION } from '$lib/constants';
	import { AdminService, type Project } from '$lib/services/index.js';
	import { Bot, Trash2 } from 'lucide-svelte';
	import { fade } from 'svelte/transition';

	let { data } = $props();
	const { projects: initialProjects, users } = data;
	let deletingProject = $state<Project | undefined>(undefined);
	let projects = $state(initialProjects);
	let projectTableData = $derived(
		projects.map((project) => ({
			...project,
			createdBy: users.find((user) => user.id === project.userID)?.email ?? 'Unknown'
		}))
	);
	let loading = $state(false);

	const duration = PAGE_TRANSITION_DURATION;
</script>

<Layout>
	<div class="my-4" in:fade={{ duration }} out:fade={{ duration }}>
		<div class="flex flex-col gap-8">
			<h1 class="text-2xl font-semibold">Projects</h1>
			{#if projects.length === 0}
				<div class="mt-12 flex w-md flex-col items-center gap-4 self-center text-center">
					<Bot class="size-24 text-gray-200 dark:text-gray-900" />
					<h4 class="text-lg font-semibold text-gray-400 dark:text-gray-600">
						No created projects
					</h4>
					<p class="text-sm font-light text-gray-400 dark:text-gray-600">
						Projects are generated by the system when a user begins a chat or sets up a MCP server.
					</p>
				</div>
			{:else}
				<Table
					data={projectTableData}
					fields={['id', 'name', 'createdBy', 'created']}
					headers={[
						{ title: 'Created By', property: 'createdBy' },
						{ title: 'Created', property: 'created' }
					]}
				>
					{#snippet actions(d)}
						<button
							class="icon-button hover:text-red-500"
							onclick={(e) => {
								e.stopPropagation();
								deletingProject = d;
							}}
							use:tooltip={'Delete Project'}
						>
							<Trash2 class="size-4" />
						</button>
					{/snippet}
				</Table>
			{/if}
		</div>
	</div>
</Layout>

<Confirm
	msg={`Are you sure you want to delete this project?`}
	show={Boolean(deletingProject)}
	onsuccess={async () => {
		if (!deletingProject) return;
		loading = true;
		await AdminService.deleteProject(deletingProject.assistantID, deletingProject.id);
		projects = await AdminService.listProjects();
		loading = false;
		deletingProject = undefined;
	}}
	oncancel={() => (deletingProject = undefined)}
	{loading}
/>

<svelte:head>
	<title>Obot | Projects</title>
</svelte:head>
